// @generated effect-zero signature:sha256:4245de94c750556b1dfb847af38275fbd5dee2177a7e1175de7ce9d0f27e3026
import { createBuilder } from "@rocicorp/zero";
import type { ReadonlyJSONValue } from "@rocicorp/zero";

// This file was automatically generated by effect-zero.
// You should NOT make any changes in this file as it will be overwritten.
function customType<T>(): T {
  return null as unknown as T;
}

const configWorkspaceTable = {
  name: "configWorkspace",
  columns: {
    workspaceId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    sheetId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "sheet_id",
    },
    autoCheckin: {
      type: "boolean",
      optional: true,
      customType: customType<boolean>(),
      serverName: "auto_checkin",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["workspaceId"],
  serverName: "sheet_db_config_workspace",
} as const;
const configWorkspaceMonitorRoleTable = {
  name: "configWorkspaceMonitorRole",
  columns: {
    workspaceId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    roleId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "role_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["workspaceId", "roleId"],
  serverName: "sheet_db_config_workspace_monitor_role",
} as const;
const configWorkspaceFeatureFlagTable = {
  name: "configWorkspaceFeatureFlag",
  columns: {
    workspaceId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    flagName: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "flag_name",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["workspaceId", "flagName"],
  serverName: "sheet_db_config_workspace_feature_flag",
} as const;
const configWorkspaceUpdateAnnouncementDeliveryTable = {
  name: "configWorkspaceUpdateAnnouncementDelivery",
  columns: {
    workspaceId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    announcementId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "announcement_id",
    },
    publishedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "published_at",
    },
    deliveredAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "delivered_at",
    },
    conversationId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "conversation_id",
    },
    messageId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "message_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["workspaceId", "announcementId"],
  serverName: "sheet_db_config_workspace_update_announcement_delivery",
} as const;
const configUserPlatformTable = {
  name: "configUserPlatform",
  columns: {
    platform: {
      type: "string",
      optional: false,
      customType: customType<string>(),
    },
    userId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "user_id",
    },
    defaultClientId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "default_client_id",
    },
    checkinDmEnabled: {
      type: "boolean",
      optional: false,
      customType: customType<boolean>(),
      serverName: "checkin_dm_enabled",
    },
    monitorDmEnabled: {
      type: "boolean",
      optional: false,
      customType: customType<boolean>(),
      serverName: "monitor_dm_enabled",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["platform", "userId"],
  serverName: "sheet_db_config_user_platform",
} as const;
const configWorkspaceConversationTable = {
  name: "configWorkspaceConversation",
  columns: {
    workspaceId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    conversationId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "conversation_id",
    },
    name: {
      type: "string",
      optional: true,
      customType: customType<string>(),
    },
    running: {
      type: "boolean",
      optional: true,
      customType: customType<boolean>(),
    },
    roleId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "role_id",
    },
    checkinConversationId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "checkin_conversation_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["workspaceId", "conversationId"],
  serverName: "sheet_db_config_workspace_conversation",
} as const;
const configWorkspaceTeamSubmissionChannelTable = {
  name: "configWorkspaceTeamSubmissionChannel",
  columns: {
    workspaceId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    conversationId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "conversation_id",
    },
    destinationTeamConfigName: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "destination_team_config_name",
    },
    writeMode: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "write_mode",
    },
    removedRowStrategy: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "removed_row_strategy",
    },
    requireValidOshi: {
      type: "boolean",
      optional: false,
      customType: customType<boolean>(),
      serverName: "require_valid_oshi",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["workspaceId", "conversationId"],
  serverName: "sheet_db_config_workspace_team_submission_channel",
} as const;
const messageSlotTable = {
  name: "messageSlot",
  columns: {
    clientPlatform: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_platform",
    },
    clientId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_id",
    },
    messageId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "message_id",
    },
    day: {
      type: "number",
      optional: false,
      customType: customType<number>(),
    },
    workspaceId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    conversationId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "conversation_id",
    },
    createdByUserId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "created_by_user_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["clientPlatform", "clientId", "messageId"],
  serverName: "sheet_db_message_slot",
} as const;
const messageCheckinTable = {
  name: "messageCheckin",
  columns: {
    clientPlatform: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_platform",
    },
    clientId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_id",
    },
    messageId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "message_id",
    },
    initialMessage: {
      type: "json",
      optional: false,
      customType: customType<ReadonlyJSONValue>(),
      serverName: "initial_message",
    },
    hour: {
      type: "number",
      optional: false,
      customType: customType<number>(),
    },
    runningConversationId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "running_conversation_id",
    },
    roleId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "role_id",
    },
    workspaceId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    conversationId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "conversation_id",
    },
    createdByUserId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "created_by_user_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["clientPlatform", "clientId", "messageId"],
  serverName: "sheet_db_message_checkin",
} as const;
const messageCheckinMemberTable = {
  name: "messageCheckinMember",
  columns: {
    clientPlatform: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_platform",
    },
    clientId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_id",
    },
    messageId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "message_id",
    },
    memberId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "member_id",
    },
    checkinAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "checkin_at",
    },
    checkinClaimId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "checkin_claim_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["clientPlatform", "clientId", "messageId", "memberId"],
  serverName: "sheet_db_message_checkin_member",
} as const;
const messageRoomOrderTable = {
  name: "messageRoomOrder",
  columns: {
    clientPlatform: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_platform",
    },
    clientId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_id",
    },
    messageId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "message_id",
    },
    previousFills: {
      type: "json",
      optional: false,
      customType: customType<ReadonlyArray<string>>(),
      serverName: "previous_fills",
    },
    fills: {
      type: "json",
      optional: false,
      customType: customType<ReadonlyArray<string>>(),
    },
    hour: {
      type: "number",
      optional: false,
      customType: customType<number>(),
    },
    rank: {
      type: "number",
      optional: false,
      customType: customType<number>(),
    },
    tentative: {
      type: "boolean",
      optional: false,
      customType: customType<boolean>(),
    },
    monitor: {
      type: "string",
      optional: true,
      customType: customType<string>(),
    },
    workspaceId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    conversationId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "conversation_id",
    },
    createdByUserId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "created_by_user_id",
    },
    sendClaimId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "send_claim_id",
    },
    sendClaimedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "send_claimed_at",
    },
    sentMessageId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "sent_message_id",
    },
    sentConversationId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "sent_conversation_id",
    },
    sentAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "sent_at",
    },
    tentativeUpdateClaimId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "tentative_update_claim_id",
    },
    tentativeUpdateClaimedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "tentative_update_claimed_at",
    },
    tentativePinClaimId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "tentative_pin_claim_id",
    },
    tentativePinClaimedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "tentative_pin_claimed_at",
    },
    tentativePinnedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "tentative_pinned_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["clientPlatform", "clientId", "messageId"],
  serverName: "sheet_db_message_room_order",
} as const;
const messageRoomOrderEntryTable = {
  name: "messageRoomOrderEntry",
  columns: {
    clientPlatform: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_platform",
    },
    clientId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_id",
    },
    messageId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "message_id",
    },
    rank: {
      type: "number",
      optional: false,
      customType: customType<number>(),
    },
    position: {
      type: "number",
      optional: false,
      customType: customType<number>(),
    },
    hour: {
      type: "number",
      optional: false,
      customType: customType<number>(),
    },
    team: {
      type: "string",
      optional: false,
      customType: customType<string>(),
    },
    tags: {
      type: "json",
      optional: false,
      customType: customType<ReadonlyArray<string>>(),
    },
    effectValue: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "effect_value",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["clientPlatform", "clientId", "messageId", "rank", "position"],
  serverName: "sheet_db_message_room_order_entry",
} as const;
const messageTeamSubmissionTable = {
  name: "messageTeamSubmission",
  columns: {
    workspaceId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "workspace_id",
    },
    conversationId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "conversation_id",
    },
    messageId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "message_id",
    },
    clientPlatform: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_platform",
    },
    clientId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "client_id",
    },
    discordGuildId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "discord_guild_id",
    },
    discordChannelId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "discord_channel_id",
    },
    discordAuthorId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "discord_author_id",
    },
    sheetId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "sheet_id",
    },
    confirmationMessageId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "confirmation_message_id",
    },
    parsedSubmission: {
      type: "json",
      optional: false,
      customType: customType<ReadonlyJSONValue>(),
      serverName: "parsed_submission",
    },
    rowMappings: {
      type: "json",
      optional: false,
      customType: customType<ReadonlyJSONValue>(),
      serverName: "row_mappings",
    },
    rollbackSnapshot: {
      type: "json",
      optional: true,
      customType: customType<ReadonlyJSONValue>(),
      serverName: "rollback_snapshot",
    },
    version: {
      type: "number",
      optional: false,
      customType: customType<number>(),
    },
    status: {
      type: "string",
      optional: false,
      customType: customType<string>(),
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["workspaceId", "conversationId", "messageId"],
  serverName: "sheet_db_message_team_submission",
} as const;
const sheetApisDispatchJobsTable = {
  name: "sheetApisDispatchJobs",
  columns: {
    dispatchRequestId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "dispatch_request_id",
    },
    entityType: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "entity_type",
    },
    entityId: {
      type: "string",
      optional: false,
      customType: customType<string>(),
      serverName: "entity_id",
    },
    operation: {
      type: "string",
      optional: false,
      customType: customType<string>(),
    },
    status: {
      type: "string",
      optional: false,
      customType: customType<string>(),
    },
    runId: {
      type: "string",
      optional: true,
      customType: customType<string>(),
      serverName: "run_id",
    },
    payload: {
      type: "json",
      optional: false,
      customType: customType<ReadonlyJSONValue>(),
    },
    result: {
      type: "json",
      optional: true,
      customType: customType<ReadonlyJSONValue>(),
    },
    error: {
      type: "json",
      optional: true,
      customType: customType<ReadonlyJSONValue>(),
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: customType<number>(),
      serverName: "updated_at",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: customType<number>(),
      serverName: "deleted_at",
    },
  },
  primaryKey: ["dispatchRequestId"],
  serverName: "sheet_db_sheet_apis_dispatch_jobs",
} as const;
export const schema = {
  tables: {
    configWorkspace: configWorkspaceTable,
    configWorkspaceMonitorRole: configWorkspaceMonitorRoleTable,
    configWorkspaceFeatureFlag: configWorkspaceFeatureFlagTable,
    configWorkspaceUpdateAnnouncementDelivery: configWorkspaceUpdateAnnouncementDeliveryTable,
    configUserPlatform: configUserPlatformTable,
    configWorkspaceConversation: configWorkspaceConversationTable,
    configWorkspaceTeamSubmissionChannel: configWorkspaceTeamSubmissionChannelTable,
    messageSlot: messageSlotTable,
    messageCheckin: messageCheckinTable,
    messageCheckinMember: messageCheckinMemberTable,
    messageRoomOrder: messageRoomOrderTable,
    messageRoomOrderEntry: messageRoomOrderEntryTable,
    messageTeamSubmission: messageTeamSubmissionTable,
    sheetApisDispatchJobs: sheetApisDispatchJobsTable,
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

export type Schema = typeof schema;

export const zql = createBuilder(schema);
export const builder = zql;
