packages:
  - packages/*

allowBuilds:
  "@rocicorp/zero-sqlite3": true
  better-sqlite3: true
  core-js: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false

catalog:
  {
    "@effect/atom-react": npm:@effect/atom-react@4.0.0-beta.56,
    "@effect/ai-openai": npm:@effect/ai-openai@4.0.0-beta.56,
    "@effect/ai-openrouter": npm:@effect/ai-openrouter@4.0.0-beta.56,
    "@effect/vitest": npm:@effect/vitest@4.0.0-beta.56,
    "@effect/platform-node": npm:@effect/platform-node@4.0.0-beta.56,
    "@effect/opentelemetry": npm:@effect/opentelemetry@4.0.0-beta.56,
    "@effect/sql-sqlite-node": npm:@effect/sql-sqlite-node@4.0.0-beta.56,
    dfx: npm:dfx@1.0.13,
    effect: npm:effect@4.0.0-beta.56,
    vite: npm:@voidzero-dev/vite-plus-core@0.1.15,
    vitest: npm:@voidzero-dev/vite-plus-test@0.1.15,
    vite-plus: 0.1.15,
  }

ignoredBuiltDependencies: []
overrides:
  better-auth: 1.4.18
  vite: "catalog:"
  vitest: "catalog:"
patchedDependencies:
  better-auth@1.4.18: patches/better-auth@1.4.18.patch
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
