packages:
  - packages/*

catalog:
  {
    "@effect/atom-react": npm:@effect/atom-react@4.0.0-beta.56,
    "@effect/ai-openai": npm:@effect/ai-openai@4.0.0-beta.56,
    "@effect/ai-openrouter": npm:@effect/ai-openrouter@4.0.0-beta.56,
    "@effect/vitest": npm:@effect/vitest@4.0.0-beta.56,
    "@effect/platform-node": npm:@effect/platform-node@4.0.0-beta.56,
    "@effect/opentelemetry": npm:@effect/opentelemetry@4.0.0-beta.56,
    "@effect/sql-sqlite-node": npm:@effect/sql-sqlite-node@4.0.0-beta.56,
    dfx: npm:dfx@1.0.13,
    effect: npm:effect@4.0.0-beta.56,
    vite: npm:@voidzero-dev/vite-plus-core@0.1.15,
    vitest: npm:@voidzero-dev/vite-plus-test@0.1.15,
    vite-plus: 0.1.15,
  }

ignoredBuiltDependencies: []
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
