packages:
  - packages/*

allowBuilds:
  "@rocicorp/zero-sqlite3": true
  better-sqlite3: true
  core-js: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false

catalog:
  {
    "@effect/atom-react": npm:@effect/atom-react@4.0.0-beta.67,
    "@effect/ai-openai": npm:@effect/ai-openai@4.0.0-beta.67,
    "@effect/ai-openrouter": npm:@effect/ai-openrouter@4.0.0-beta.67,
    "@effect/vitest": npm:@tiara-stack/effect-vitest@4.0.0-beta.93.tiara.2,
    "@effect/platform-node": npm:@effect/platform-node@4.0.0-beta.67,
    "@effect/opentelemetry": npm:@effect/opentelemetry@4.0.0-beta.67,
    "@effect/sql-sqlite-node": npm:@effect/sql-sqlite-node@4.0.0-beta.67,
    "@effect/sql-pg": npm:@effect/sql-pg@4.0.0-beta.67,
    "@types/node": ^24.7.2,
    dfx: npm:dfx@1.0.13,
    effect: npm:effect@4.0.0-beta.67,
    tsx: npm:tsx@4.22.3,
    vite: npm:@voidzero-dev/vite-plus-core@0.2.2,
    vitest: 4.1.9,
    vite-plus: npm:@tiara-stack/vite-plus@0.2.4,
  }

ignoredBuiltDependencies: []
overrides:
  "@tiara-stack/tsgo-effect": 0.1.2
  "@tiara-stack/tsgolint-effect": 0.1.2
  better-auth: 1.6.16
  vite: "catalog:"
  vitest: "catalog:"
patchedDependencies:
  better-auth@1.6.16: patches/better-auth@1.6.16.patch
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
