import { Cause, Context, Effect, Layer, Match, Option, Predicate, Ref, Schema } from "effect";
import { ClusterError } from "effect/unstable/cluster";
import { Workflow, WorkflowEngine } from "effect/unstable/workflow";
import { WorkflowCommandExecutor } from "./dispatcher";
import {
  parseWorkflowEventId,
  WorkflowEventCommandPayload,
  type AnyWorkflowEvent,
  type WorkflowEventId,
} from "./event";
import {
  WorkflowStore,
  type WorkflowCommand,
  type WorkflowJson,
  type WorkflowRun,
  type WorkflowRunCursor,
  type WorkflowStoreService,
} from "./store";

type WorkflowPayloadSchema = Workflow.AnyStructSchema & {
  readonly DecodingServices: never;
  readonly EncodingServices: never;
};

type WorkflowResultSchema = Schema.Top & {
  readonly DecodingServices: never;
};

export type WorkflowDefinition = Omit<
  Workflow.Any,
  "errorSchema" | "payloadSchema" | "successSchema"
> & {
  readonly payloadSchema: WorkflowPayloadSchema;
  readonly successSchema: WorkflowResultSchema;
  readonly errorSchema: WorkflowResultSchema;
};

export type RunnableWorkflow = WorkflowDefinition & {
  readonly execute: (
    payload: unknown,
    options: { readonly discard: true },
  ) => Effect.Effect<string, never, WorkflowEngine.WorkflowEngine>;
  readonly poll: (
    executionId: string,
  ) => Effect.Effect<
    Option.Option<Workflow.Result<unknown, unknown>>,
    never,
    WorkflowEngine.WorkflowEngine
  >;
  readonly interrupt: (
    executionId: string,
  ) => Effect.Effect<void, never, WorkflowEngine.WorkflowEngine>;
  readonly resume: (
    executionId: string,
  ) => Effect.Effect<void, never, WorkflowEngine.WorkflowEngine>;
};

export type WorkflowRuntimeOptions = {
  readonly workflows: ReadonlyArray<WorkflowDefinition>;
  readonly events?: ReadonlyArray<AnyWorkflowEvent> | undefined;
  readonly definitionVersion?: ((workflow: WorkflowDefinition) => string) | undefined;
};

export interface WorkflowRuntimeService {
  readonly workflow: (name: string) => Effect.Effect<RunnableWorkflow, Error>;
  readonly event: (eventId: WorkflowEventId) => Effect.Effect<AnyWorkflowEvent, Error>;
  readonly version: (workflow: WorkflowDefinition) => string;
}

export class WorkflowRuntime extends Context.Service<WorkflowRuntime, WorkflowRuntimeService>()(
  "effect-zero-workflow/WorkflowRuntime",
) {}

const asRunnableWorkflow = (workflow: WorkflowDefinition): RunnableWorkflow => {
  const operationNames = ["execute", "poll", "interrupt", "resume"] as const;
  for (const operationName of operationNames) {
    if (
      !Predicate.hasProperty(operationName)(workflow) ||
      !Predicate.isFunction(workflow[operationName])
    ) {
      throw new Error(`Workflow ${workflow.name} is missing operation: ${operationName}`);
    }
  }
  return workflow as RunnableWorkflow;
};

export const makeWorkflowRuntime = (options: WorkflowRuntimeOptions): WorkflowRuntimeService => {
  const workflowsByName = new Map<string, RunnableWorkflow>();
  for (const workflow of options.workflows) {
    if (workflowsByName.has(workflow.name)) {
      throw new Error(`Duplicate workflow registration: ${workflow.name}`);
    }
    workflowsByName.set(workflow.name, asRunnableWorkflow(workflow));
  }
  const eventsByName = new Map<string, AnyWorkflowEvent>();
  for (const event of options.events ?? []) {
    if (eventsByName.has(event.name)) {
      throw new Error(`Duplicate workflow event registration: ${event.name}`);
    }
    eventsByName.set(event.name, event);
  }
  return {
    workflow: (name) =>
      Option.fromNullishOr(workflowsByName.get(name)).pipe(
        Option.match({
          onNone: () => Effect.fail(new Error(`Unknown workflow: ${name}`)),
          onSome: Effect.succeed,
        }),
      ),
    event: (eventId) =>
      parseWorkflowEventId(eventId).pipe(
        Effect.mapError((error) => new Error(error.message)),
        Effect.flatMap(({ eventName }) =>
          Option.fromNullishOr(eventsByName.get(eventName)).pipe(
            Option.match({
              onNone: () => Effect.fail(new Error(`Unknown workflow event: ${eventName}`)),
              onSome: Effect.succeed,
            }),
          ),
        ),
      ),
    version: options.definitionVersion ?? (() => "1"),
  };
};

export const workflowRuntimeLayer = (
  options: WorkflowRuntimeOptions,
): Layer.Layer<WorkflowRuntime> => Layer.sync(WorkflowRuntime, () => makeWorkflowRuntime(options));

const encodeWorkflowPayload = (workflow: WorkflowDefinition, payload: unknown) =>
  Schema.encodeUnknownEffect(workflow.payloadSchema)(payload).pipe(
    Effect.flatMap(Schema.decodeUnknownEffect(Schema.Json)),
  );

export type EnqueueWorkflowDefinitionOptions = {
  /** Stable invocation identity, generated by the caller before optimistic mutation. */
  readonly runId: string;
  readonly visibilityKey: string;
  readonly principal?: WorkflowJson | undefined;
  readonly maxAttempts?: number | undefined;
  readonly runAfter?: Date | undefined;
};

export const enqueueWorkflowDefinition = (
  workflow: WorkflowDefinition,
  payload: unknown,
  options: EnqueueWorkflowDefinitionOptions,
) =>
  Effect.gen(function* () {
    const store = yield* WorkflowStore;
    const runtime = yield* WorkflowRuntime;
    const executionId = yield* workflow.executionId(payload);
    const encodedPayload = yield* encodeWorkflowPayload(workflow, payload);
    return yield* store.enqueue({
      runId: options.runId,
      workflowName: workflow.name,
      definitionVersion: runtime.version(workflow),
      executionId,
      idempotencyKey: executionId,
      visibilityKey: options.visibilityKey,
      principal: options.principal,
      payload: encodedPayload,
      maxAttempts: options.maxAttempts,
      runAfter: options.runAfter,
    });
  });

const withWorkflowEngine =
  (engine: WorkflowEngine.WorkflowEngine["Service"]) =>
  <A, E>(effect: Effect.Effect<A, E, WorkflowEngine.WorkflowEngine>) =>
    effect.pipe(Effect.provideService(WorkflowEngine.WorkflowEngine, engine));

const executeStartCommand = (
  command: WorkflowCommand,
  workflow: RunnableWorkflow,
  engine: WorkflowEngine.WorkflowEngine["Service"],
  store: WorkflowStoreService,
) =>
  Effect.gen(function* () {
    const payload = yield* Schema.decodeUnknownEffect(workflow.payloadSchema)(command.payload);
    const executionId = yield* withWorkflowEngine(engine)(
      workflow.execute(payload, { discard: true }),
    );
    if (executionId !== command.executionId) {
      yield* withWorkflowEngine(engine)(workflow.interrupt(executionId));
      return yield* Effect.fail(
        new Error(
          `Workflow execution id mismatch for ${command.workflowName}: expected ${command.executionId}, received ${executionId}`,
        ),
      );
    }
    yield* store.markRun(command.runId, "running");
  });

const executeWorkflowCommand = (
  command: WorkflowCommand,
  runtime: WorkflowRuntimeService,
  engine: WorkflowEngine.WorkflowEngine["Service"],
  store: WorkflowStoreService,
) =>
  Effect.gen(function* () {
    const workflow = yield* runtime.workflow(command.workflowName);
    const currentVersion = runtime.version(workflow);
    if (currentVersion !== command.definitionVersion) {
      return yield* Effect.fail(
        new Error(
          `Workflow definition version mismatch for ${command.workflowName}: queued ${command.definitionVersion}, registered ${currentVersion}`,
        ),
      );
    }
    return yield* Match.value(command.kind).pipe(
      Match.when("start", () => executeStartCommand(command, workflow, engine, store)),
      Match.when("cancel", () =>
        withWorkflowEngine(engine)(workflow.interrupt(command.executionId)).pipe(
          Effect.andThen(store.markRun(command.runId, "cancelled")),
        ),
      ),
      Match.when("resume", () =>
        withWorkflowEngine(engine)(workflow.resume(command.executionId)).pipe(
          Effect.andThen(store.markRun(command.runId, "running")),
        ),
      ),
      Match.when("event", () =>
        Effect.gen(function* () {
          const payload = yield* Schema.decodeUnknownEffect(WorkflowEventCommandPayload)(
            command.payload,
          );
          const parsed = yield* parseWorkflowEventId(payload.eventId);
          if (
            parsed.workflowName !== command.workflowName ||
            parsed.executionId !== command.executionId
          ) {
            return yield* Effect.fail(
              new Error(
                `Workflow event ${payload.eventId} does not belong to execution ${command.executionId}`,
              ),
            );
          }
          const event = yield* runtime.event(payload.eventId);
          yield* withWorkflowEngine(engine)(event.sendUnknown(payload.eventId, payload.value));
          yield* store.markRun(command.runId, "running");
        }),
      ),
      Match.exhaustive,
    );
  });

export const workflowRuntimeCommandExecutorLayer = Layer.effect(
  WorkflowCommandExecutor,
  Effect.gen(function* () {
    const runtime = yield* WorkflowRuntime;
    const engine = yield* WorkflowEngine.WorkflowEngine;
    const store = yield* WorkflowStore;
    return {
      execute: (command: WorkflowCommand) =>
        executeWorkflowCommand(command, runtime, engine, store),
    };
  }),
);

const jsonOrDescription = (value: unknown): WorkflowJson =>
  Option.match(Schema.decodeUnknownOption(Schema.Json)(value), {
    onNone: () => {
      try {
        return { description: JSON.stringify(value) ?? String(value) };
      } catch {
        return { description: String(value) };
      }
    },
    onSome: (json) => json,
  });

const hasMalformedMessageDefect = (cause: Cause.Cause<unknown>) =>
  cause.reasons.some(
    (reason) =>
      (Cause.isFailReason(reason) && ClusterError.MalformedMessage.is(reason.error)) ||
      (Cause.isDieReason(reason) && ClusterError.MalformedMessage.is(reason.defect)),
  );

const markRunFailedAfterPermanentReconciliationError = (
  run: WorkflowRun,
  store: WorkflowStoreService,
  options: {
    readonly reconciliationCause: string;
    readonly errorMessage: string;
    readonly successLog: string;
    readonly failureLog: string;
  },
) => {
  const runAnnotations = {
    executionId: run.executionId,
    runId: run.runId,
    workflowName: run.workflowName,
  };
  return store
    .markRun(run.runId, "failed", {
      error: { message: options.errorMessage },
    })
    .pipe(
      Effect.tap(() =>
        Effect.logWarning(options.successLog).pipe(
          Effect.annotateLogs({
            ...runAnnotations,
            cause: options.reconciliationCause,
          }),
        ),
      ),
      Effect.tapCause((markingCause) =>
        Effect.logError(options.failureLog).pipe(
          Effect.annotateLogs({
            ...runAnnotations,
            markingCause: Cause.pretty(markingCause),
            reconciliationCause: options.reconciliationCause,
          }),
        ),
      ),
      Effect.ignore,
    );
};

const reconcileRun = (
  run: WorkflowRun,
  runtime: WorkflowRuntimeService,
  engine: WorkflowEngine.WorkflowEngine["Service"],
  store: WorkflowStoreService,
) =>
  Effect.gen(function* () {
    const workflow = yield* runtime.workflow(run.workflowName);
    const result = yield* withWorkflowEngine(engine)(workflow.poll(run.executionId));
    return yield* Match.valueTags(result, {
      None: () => Effect.void,
      Some: ({ value }) =>
        Match.valueTags(value, {
          Suspended: () => Effect.void,
          Complete: ({ exit }) =>
            Match.valueTags(exit, {
              Success: ({ value }) =>
                store.markRun(run.runId, "succeeded", {
                  result: jsonOrDescription(value),
                }),
              Failure: ({ cause }) =>
                store.markRun(run.runId, "failed", {
                  error: {
                    message: Cause.pretty(cause),
                  },
                }),
            }),
        }),
    });
  }).pipe(
    Effect.catchCause((cause) => {
      if (Cause.hasInterrupts(cause)) {
        return Effect.interrupt;
      }
      // Workflow.poll converts remote result-decoding failures to defects with
      // Effect.orDie. The execution is already terminal in storage, so record
      // that defect once instead of warning on every reconciliation forever.
      if (hasMalformedMessageDefect(cause)) {
        const reconciliationCause = Cause.pretty(cause);
        return markRunFailedAfterPermanentReconciliationError(run, store, {
          reconciliationCause,
          errorMessage: `Workflow execution state could not be decoded: ${reconciliationCause}`,
          successLog: "Marked workflow run as failed after undecodable execution state",
          failureLog: "Failed to mark workflow run after undecodable execution state",
        });
      }
      return Effect.logWarning("Failed to reconcile workflow run").pipe(
        Effect.annotateLogs({
          cause: Cause.pretty(cause),
          executionId: run.executionId,
          runId: run.runId,
          workflowName: run.workflowName,
        }),
      );
    }),
  );

export type WorkflowReconciliationOptions = {
  readonly batchSize?: number | undefined;
  readonly concurrency?: number | undefined;
  readonly cursor?: Ref.Ref<WorkflowRunCursor | undefined> | undefined;
};

export const reconcileWorkflowRuns = (options: WorkflowReconciliationOptions = {}) =>
  Effect.gen(function* () {
    const runtime = yield* WorkflowRuntime;
    const engine = yield* WorkflowEngine.WorkflowEngine;
    const store = yield* WorkflowStore;
    const cursor = Predicate.isUndefined(options.cursor)
      ? undefined
      : yield* Ref.get(options.cursor);
    const listed = yield* store.listRuns("running", options.batchSize ?? 100, cursor).pipe(
      Effect.map(Option.some),
      Effect.catchCause((cause) =>
        Cause.hasInterrupts(cause)
          ? Effect.interrupt
          : Effect.logError("Failed to list workflow runs for reconciliation", cause).pipe(
              Effect.as(Option.none<ReadonlyArray<WorkflowRun>>()),
            ),
      ),
    );
    if (Option.isNone(listed)) {
      return 0;
    }
    const runs = listed.value;
    const lastRun = runs.at(-1);
    yield* Effect.forEach(runs, (run) => reconcileRun(run, runtime, engine, store), {
      concurrency: options.concurrency ?? 10,
      discard: true,
    });
    if (Predicate.isNotUndefined(options.cursor)) {
      yield* Ref.set(
        options.cursor,
        Predicate.isUndefined(lastRun)
          ? undefined
          : { runId: lastRun.runId, updatedAt: lastRun.updatedAt },
      );
    }
    return runs.length;
  });
