import { DispatchClusterWorkflows } from "../dispatchWorkflows";

export const {
  DispatchAutoCheckinTestWorkflow,
  DispatchCheckinButtonWorkflow,
  DispatchCheckinWorkflow,
  DispatchConversationListConfigWorkflow,
  DispatchConversationLockdownSetupWorkflow,
  DispatchConversationLockdownUndoWorkflow,
  DispatchConversationSetWorkflow,
  DispatchConversationUnsetWorkflow,
  DispatchWorkspaceWelcomeWorkflow,
  DispatchKickWorkflow,
  DispatchPreferenceDmDisableWorkflow,
  DispatchPreferenceDmEnableWorkflow,
  DispatchPreferenceDmSetClientWorkflow,
  DispatchPreferenceDmStatusWorkflow,
  DispatchRoomOrderNextButtonWorkflow,
  DispatchRoomOrderPinTentativeButtonWorkflow,
  DispatchRoomOrderPreviousButtonWorkflow,
  DispatchRoomOrderSendButtonWorkflow,
  DispatchRoomOrderWorkflow,
  DispatchScheduleListWorkflow,
  DispatchServiceAddWorkspaceFeatureFlagWorkflow,
  DispatchServiceRemoveWorkspaceFeatureFlagWorkflow,
  DispatchServiceStatusWorkflow,
  DispatchWorkspaceAddMonitorRoleWorkflow,
  DispatchWorkspaceListConfigWorkflow,
  DispatchWorkspaceRemoveMonitorRoleWorkflow,
  DispatchWorkspaceSetAutoCheckinWorkflow,
  DispatchWorkspaceSetMonitorChannelWorkflow,
  DispatchWorkspaceSetSheetWorkflow,
  DispatchWorkspaceUnsetMonitorChannelWorkflow,
  DispatchScreenshotWorkflow,
  DispatchSlotButtonWorkflow,
  DispatchSlotListWorkflow,
  DispatchSlotOpenButtonWorkflow,
  DispatchTeamListWorkflow,
  DispatchTeamSubmissionConfirmButtonWorkflow,
  DispatchTeamSubmissionRejectButtonWorkflow,
  DispatchTeamSubmissionWorkflow,
  DispatchUpdateAnnouncementWorkflow,
  all: DispatchWorkflows,
} = DispatchClusterWorkflows;
