apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheet-web
  labels:
    app: sheet-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheet-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sheet-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: sheet-web
          image: <IMAGE>
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 3000
              name: sheet-web-svc
            - containerPort: 9464
              name: sheet-web-met
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sheet-web-secret
                  key: otelExporterOtlpEndpoint
            - name: AUTH_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: sheet-web-secret
                  key: authBaseUrl
            - name: APP_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: sheet-web-secret
                  key: appBaseUrl
            - name: SHEET_APIS_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: sheet-web-secret
                  key: sheetApisBaseUrl
          volumeMounts:
            - name: sheet-web-ca-certificate
              readOnly: true
              mountPath: "/usr/local/share/ca-certificates/tiarastack"
            - name: sheet-web-tmp
              mountPath: "/tmp"
      serviceAccountName: sheet-web
      volumes:
        - name: sheet-web-ca-certificate
          configMap:
            name: sheet-web-ca-certificate
            items:
              - key: ca-certificate.crt
                path: tiarastack.crt
        - name: sheet-web-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sheet-web-service
  labels:
    app: sheet-web
spec:
  ports:
    - name: sheet-web-svc
      protocol: TCP
      port: 80
      targetPort: sheet-web-svc
    - name: sheet-web-met
      protocol: TCP
      port: 9464
      targetPort: sheet-web-met
  selector:
    app: sheet-web
