/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardShiftsRouteImport } from './routes/dashboard/shifts'
import { Route as DashboardGuildsRouteRouteImport } from './routes/dashboard/guilds/route'
import { Route as DashboardGuildsIndexRouteImport } from './routes/dashboard/guilds/index'
import { Route as DashboardGuildsGuildIdScheduleRouteRouteImport } from './routes/dashboard/guilds/$guildId.schedule/route'
import { Route as DashboardGuildsGuildIdScheduleDailyRouteImport } from './routes/dashboard/guilds/$guildId.schedule/daily'
import { Route as DashboardGuildsGuildIdScheduleCalendarRouteImport } from './routes/dashboard/guilds/$guildId.schedule/calendar'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardShiftsRoute = DashboardShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGuildsRouteRoute = DashboardGuildsRouteRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGuildsIndexRoute = DashboardGuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildsRouteRoute,
} as any)
const DashboardGuildsGuildIdScheduleRouteRoute =
  DashboardGuildsGuildIdScheduleRouteRouteImport.update({
    id: '/$guildId/schedule',
    path: '/$guildId/schedule',
    getParentRoute: () => DashboardGuildsRouteRoute,
  } as any)
const DashboardGuildsGuildIdScheduleDailyRoute =
  DashboardGuildsGuildIdScheduleDailyRouteImport.update({
    id: '/daily',
    path: '/daily',
    getParentRoute: () => DashboardGuildsGuildIdScheduleRouteRoute,
  } as any)
const DashboardGuildsGuildIdScheduleCalendarRoute =
  DashboardGuildsGuildIdScheduleCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => DashboardGuildsGuildIdScheduleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/guilds': typeof DashboardGuildsRouteRouteWithChildren
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/guilds/': typeof DashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardGuildsGuildIdScheduleRouteRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/calendar': typeof DashboardGuildsGuildIdScheduleCalendarRoute
  '/dashboard/guilds/$guildId/schedule/daily': typeof DashboardGuildsGuildIdScheduleDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/guilds': typeof DashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardGuildsGuildIdScheduleRouteRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/calendar': typeof DashboardGuildsGuildIdScheduleCalendarRoute
  '/dashboard/guilds/$guildId/schedule/daily': typeof DashboardGuildsGuildIdScheduleDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/guilds': typeof DashboardGuildsRouteRouteWithChildren
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/guilds/': typeof DashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardGuildsGuildIdScheduleRouteRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/calendar': typeof DashboardGuildsGuildIdScheduleCalendarRoute
  '/dashboard/guilds/$guildId/schedule/daily': typeof DashboardGuildsGuildIdScheduleDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/shifts'
    | '/dashboard/'
    | '/dashboard/guilds/'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/calendar'
    | '/dashboard/guilds/$guildId/schedule/daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/shifts'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/calendar'
    | '/dashboard/guilds/$guildId/schedule/daily'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/shifts'
    | '/dashboard/'
    | '/dashboard/guilds/'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/calendar'
    | '/dashboard/guilds/$guildId/schedule/daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shifts': {
      id: '/dashboard/shifts'
      path: '/shifts'
      fullPath: '/dashboard/shifts'
      preLoaderRoute: typeof DashboardShiftsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/guilds': {
      id: '/dashboard/guilds'
      path: '/guilds'
      fullPath: '/dashboard/guilds'
      preLoaderRoute: typeof DashboardGuildsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/guilds/': {
      id: '/dashboard/guilds/'
      path: '/'
      fullPath: '/dashboard/guilds/'
      preLoaderRoute: typeof DashboardGuildsIndexRouteImport
      parentRoute: typeof DashboardGuildsRouteRoute
    }
    '/dashboard/guilds/$guildId/schedule': {
      id: '/dashboard/guilds/$guildId/schedule'
      path: '/$guildId/schedule'
      fullPath: '/dashboard/guilds/$guildId/schedule'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleRouteRouteImport
      parentRoute: typeof DashboardGuildsRouteRoute
    }
    '/dashboard/guilds/$guildId/schedule/daily': {
      id: '/dashboard/guilds/$guildId/schedule/daily'
      path: '/daily'
      fullPath: '/dashboard/guilds/$guildId/schedule/daily'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleDailyRouteImport
      parentRoute: typeof DashboardGuildsGuildIdScheduleRouteRoute
    }
    '/dashboard/guilds/$guildId/schedule/calendar': {
      id: '/dashboard/guilds/$guildId/schedule/calendar'
      path: '/calendar'
      fullPath: '/dashboard/guilds/$guildId/schedule/calendar'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleCalendarRouteImport
      parentRoute: typeof DashboardGuildsGuildIdScheduleRouteRoute
    }
  }
}

interface DashboardGuildsGuildIdScheduleRouteRouteChildren {
  DashboardGuildsGuildIdScheduleCalendarRoute: typeof DashboardGuildsGuildIdScheduleCalendarRoute
  DashboardGuildsGuildIdScheduleDailyRoute: typeof DashboardGuildsGuildIdScheduleDailyRoute
}

const DashboardGuildsGuildIdScheduleRouteRouteChildren: DashboardGuildsGuildIdScheduleRouteRouteChildren =
  {
    DashboardGuildsGuildIdScheduleCalendarRoute:
      DashboardGuildsGuildIdScheduleCalendarRoute,
    DashboardGuildsGuildIdScheduleDailyRoute:
      DashboardGuildsGuildIdScheduleDailyRoute,
  }

const DashboardGuildsGuildIdScheduleRouteRouteWithChildren =
  DashboardGuildsGuildIdScheduleRouteRoute._addFileChildren(
    DashboardGuildsGuildIdScheduleRouteRouteChildren,
  )

interface DashboardGuildsRouteRouteChildren {
  DashboardGuildsIndexRoute: typeof DashboardGuildsIndexRoute
  DashboardGuildsGuildIdScheduleRouteRoute: typeof DashboardGuildsGuildIdScheduleRouteRouteWithChildren
}

const DashboardGuildsRouteRouteChildren: DashboardGuildsRouteRouteChildren = {
  DashboardGuildsIndexRoute: DashboardGuildsIndexRoute,
  DashboardGuildsGuildIdScheduleRouteRoute:
    DashboardGuildsGuildIdScheduleRouteRouteWithChildren,
}

const DashboardGuildsRouteRouteWithChildren =
  DashboardGuildsRouteRoute._addFileChildren(DashboardGuildsRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardGuildsRouteRoute: typeof DashboardGuildsRouteRouteWithChildren
  DashboardShiftsRoute: typeof DashboardShiftsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardGuildsRouteRoute: DashboardGuildsRouteRouteWithChildren,
  DashboardShiftsRoute: DashboardShiftsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
