/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardShiftsRouteImport } from './routes/dashboard/shifts'
import { Route as DashboardGuildsRouteRouteImport } from './routes/dashboard/guilds/route'
import { Route as DashboardGuildsIndexRouteImport } from './routes/dashboard/guilds/index'
import { Route as DashboardGuildsGuildIdScheduleRouteImport } from './routes/dashboard/guilds/$guildId.schedule'
import { Route as DashboardGuildsGuildIdScheduleChannelRouteRouteImport } from './routes/dashboard/guilds/$guildId.schedule.$channel/route'
import { Route as DashboardGuildsGuildIdScheduleChannelLayoutDailyRouteImport } from './routes/dashboard/guilds/$guildId.schedule.$channel/_layout/daily'
import { Route as DashboardGuildsGuildIdScheduleChannelLayoutCalendarRouteImport } from './routes/dashboard/guilds/$guildId.schedule.$channel/_layout/calendar'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardShiftsRoute = DashboardShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGuildsRouteRoute = DashboardGuildsRouteRouteImport.update({
  id: '/guilds',
  path: '/guilds',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGuildsIndexRoute = DashboardGuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildsRouteRoute,
} as any)
const DashboardGuildsGuildIdScheduleRoute =
  DashboardGuildsGuildIdScheduleRouteImport.update({
    id: '/$guildId/schedule',
    path: '/$guildId/schedule',
    getParentRoute: () => DashboardGuildsRouteRoute,
  } as any)
const DashboardGuildsGuildIdScheduleChannelRouteRoute =
  DashboardGuildsGuildIdScheduleChannelRouteRouteImport.update({
    id: '/$channel',
    path: '/$channel',
    getParentRoute: () => DashboardGuildsGuildIdScheduleRoute,
  } as any)
const DashboardGuildsGuildIdScheduleChannelLayoutDailyRoute =
  DashboardGuildsGuildIdScheduleChannelLayoutDailyRouteImport.update({
    id: '/_layout/daily',
    path: '/daily',
    getParentRoute: () => DashboardGuildsGuildIdScheduleChannelRouteRoute,
  } as any)
const DashboardGuildsGuildIdScheduleChannelLayoutCalendarRoute =
  DashboardGuildsGuildIdScheduleChannelLayoutCalendarRouteImport.update({
    id: '/_layout/calendar',
    path: '/calendar',
    getParentRoute: () => DashboardGuildsGuildIdScheduleChannelRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/guilds': typeof DashboardGuildsRouteRouteWithChildren
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/guilds/': typeof DashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel': typeof DashboardGuildsGuildIdScheduleChannelRouteRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel/calendar': typeof DashboardGuildsGuildIdScheduleChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/daily': typeof DashboardGuildsGuildIdScheduleChannelLayoutDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/guilds': typeof DashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel': typeof DashboardGuildsGuildIdScheduleChannelRouteRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel/calendar': typeof DashboardGuildsGuildIdScheduleChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/daily': typeof DashboardGuildsGuildIdScheduleChannelLayoutDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/guilds': typeof DashboardGuildsRouteRouteWithChildren
  '/dashboard/shifts': typeof DashboardShiftsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/guilds/': typeof DashboardGuildsIndexRoute
  '/dashboard/guilds/$guildId/schedule': typeof DashboardGuildsGuildIdScheduleRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel': typeof DashboardGuildsGuildIdScheduleChannelRouteRouteWithChildren
  '/dashboard/guilds/$guildId/schedule/$channel/_layout/calendar': typeof DashboardGuildsGuildIdScheduleChannelLayoutCalendarRoute
  '/dashboard/guilds/$guildId/schedule/$channel/_layout/daily': typeof DashboardGuildsGuildIdScheduleChannelLayoutDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/shifts'
    | '/dashboard/'
    | '/dashboard/guilds/'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel'
    | '/dashboard/guilds/$guildId/schedule/$channel/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/shifts'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel'
    | '/dashboard/guilds/$guildId/schedule/$channel/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/daily'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/guilds'
    | '/dashboard/shifts'
    | '/dashboard/'
    | '/dashboard/guilds/'
    | '/dashboard/guilds/$guildId/schedule'
    | '/dashboard/guilds/$guildId/schedule/$channel'
    | '/dashboard/guilds/$guildId/schedule/$channel/_layout/calendar'
    | '/dashboard/guilds/$guildId/schedule/$channel/_layout/daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/shifts': {
      id: '/dashboard/shifts'
      path: '/shifts'
      fullPath: '/dashboard/shifts'
      preLoaderRoute: typeof DashboardShiftsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/guilds': {
      id: '/dashboard/guilds'
      path: '/guilds'
      fullPath: '/dashboard/guilds'
      preLoaderRoute: typeof DashboardGuildsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/guilds/': {
      id: '/dashboard/guilds/'
      path: '/'
      fullPath: '/dashboard/guilds/'
      preLoaderRoute: typeof DashboardGuildsIndexRouteImport
      parentRoute: typeof DashboardGuildsRouteRoute
    }
    '/dashboard/guilds/$guildId/schedule': {
      id: '/dashboard/guilds/$guildId/schedule'
      path: '/$guildId/schedule'
      fullPath: '/dashboard/guilds/$guildId/schedule'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleRouteImport
      parentRoute: typeof DashboardGuildsRouteRoute
    }
    '/dashboard/guilds/$guildId/schedule/$channel': {
      id: '/dashboard/guilds/$guildId/schedule/$channel'
      path: '/$channel'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleChannelRouteRouteImport
      parentRoute: typeof DashboardGuildsGuildIdScheduleRoute
    }
    '/dashboard/guilds/$guildId/schedule/$channel/_layout/daily': {
      id: '/dashboard/guilds/$guildId/schedule/$channel/_layout/daily'
      path: '/daily'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/daily'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleChannelLayoutDailyRouteImport
      parentRoute: typeof DashboardGuildsGuildIdScheduleChannelRouteRoute
    }
    '/dashboard/guilds/$guildId/schedule/$channel/_layout/calendar': {
      id: '/dashboard/guilds/$guildId/schedule/$channel/_layout/calendar'
      path: '/calendar'
      fullPath: '/dashboard/guilds/$guildId/schedule/$channel/calendar'
      preLoaderRoute: typeof DashboardGuildsGuildIdScheduleChannelLayoutCalendarRouteImport
      parentRoute: typeof DashboardGuildsGuildIdScheduleChannelRouteRoute
    }
  }
}

interface DashboardGuildsGuildIdScheduleChannelRouteRouteChildren {
  DashboardGuildsGuildIdScheduleChannelLayoutCalendarRoute: typeof DashboardGuildsGuildIdScheduleChannelLayoutCalendarRoute
  DashboardGuildsGuildIdScheduleChannelLayoutDailyRoute: typeof DashboardGuildsGuildIdScheduleChannelLayoutDailyRoute
}

const DashboardGuildsGuildIdScheduleChannelRouteRouteChildren: DashboardGuildsGuildIdScheduleChannelRouteRouteChildren =
  {
    DashboardGuildsGuildIdScheduleChannelLayoutCalendarRoute:
      DashboardGuildsGuildIdScheduleChannelLayoutCalendarRoute,
    DashboardGuildsGuildIdScheduleChannelLayoutDailyRoute:
      DashboardGuildsGuildIdScheduleChannelLayoutDailyRoute,
  }

const DashboardGuildsGuildIdScheduleChannelRouteRouteWithChildren =
  DashboardGuildsGuildIdScheduleChannelRouteRoute._addFileChildren(
    DashboardGuildsGuildIdScheduleChannelRouteRouteChildren,
  )

interface DashboardGuildsGuildIdScheduleRouteChildren {
  DashboardGuildsGuildIdScheduleChannelRouteRoute: typeof DashboardGuildsGuildIdScheduleChannelRouteRouteWithChildren
}

const DashboardGuildsGuildIdScheduleRouteChildren: DashboardGuildsGuildIdScheduleRouteChildren =
  {
    DashboardGuildsGuildIdScheduleChannelRouteRoute:
      DashboardGuildsGuildIdScheduleChannelRouteRouteWithChildren,
  }

const DashboardGuildsGuildIdScheduleRouteWithChildren =
  DashboardGuildsGuildIdScheduleRoute._addFileChildren(
    DashboardGuildsGuildIdScheduleRouteChildren,
  )

interface DashboardGuildsRouteRouteChildren {
  DashboardGuildsIndexRoute: typeof DashboardGuildsIndexRoute
  DashboardGuildsGuildIdScheduleRoute: typeof DashboardGuildsGuildIdScheduleRouteWithChildren
}

const DashboardGuildsRouteRouteChildren: DashboardGuildsRouteRouteChildren = {
  DashboardGuildsIndexRoute: DashboardGuildsIndexRoute,
  DashboardGuildsGuildIdScheduleRoute:
    DashboardGuildsGuildIdScheduleRouteWithChildren,
}

const DashboardGuildsRouteRouteWithChildren =
  DashboardGuildsRouteRoute._addFileChildren(DashboardGuildsRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardGuildsRouteRoute: typeof DashboardGuildsRouteRouteWithChildren
  DashboardShiftsRoute: typeof DashboardShiftsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardGuildsRouteRoute: DashboardGuildsRouteRouteWithChildren,
  DashboardShiftsRoute: DashboardShiftsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
