apiVersion: apps/v1
kind: Deployment
metadata:
  name: sheet-db-server
  labels:
    app: sheet-db-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sheet-db-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sheet-db-server
    spec:
      containers:
        - name: sheet-db-server
          image: <IMAGE>
          ports:
            - containerPort: 3000
              name: sdbs-svc
            - containerPort: 9464
              name: sdbs-met
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: sdbs-secret
                  key: postgresUrl
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sdbs-secret
                  key: otelExporterOtlpEndpoint
          volumeMounts:
            - name: sheet-db-server-ca-certificate
              readOnly: true
              mountPath: "/usr/local/share/ca-certificates/tiarastack"
      serviceAccountName: sheet-db-server
      volumes:
        - name: sheet-db-server-ca-certificate
          configMap:
            name: sheet-db-server-ca-certificate
            items:
              - key: ca-certificate.crt
                path: tiarastack.crt
---
apiVersion: v1
kind: Service
metadata:
  name: sheet-db-server-service
  labels:
    app: sheet-db-server
spec:
  ports:
    - name: sdbs-svc
      protocol: TCP
      port: 80
      targetPort: sdbs-svc
    - name: sdbs-met
      protocol: TCP
      port: 9464
      targetPort: sdbs-met
  selector:
    app: sheet-db-server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sheet-db-server
  labels:
    app: sheet-db-server
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: sheet-db-server
  endpoints:
    - port: sdbs-met
