import { Cause, Context, Effect, Layer, Match, Option, Schema } from "effect";
import { ClusterError } from "effect/unstable/cluster";
import { Workflow, WorkflowEngine } from "effect/unstable/workflow";
import { WorkflowCommandExecutor } from "./dispatcher";
import {
  parseWorkflowEventId,
  WorkflowEventCommandPayload,
  type AnyWorkflowEvent,
  type WorkflowEventId,
} from "./event";
import {
  WorkflowStore,
  type WorkflowCommand,
  type WorkflowJson,
  type WorkflowRun,
  type WorkflowStoreService,
} from "./store";

export type RunnableWorkflow = Workflow.Any & {
  readonly execute: (
    payload: unknown,
    options: { readonly discard: true },
  ) => Effect.Effect<string, never, WorkflowEngine.WorkflowEngine>;
  readonly poll: (
    executionId: string,
  ) => Effect.Effect<
    Option.Option<Workflow.Result<unknown, unknown>>,
    never,
    WorkflowEngine.WorkflowEngine
  >;
  readonly interrupt: (
    executionId: string,
  ) => Effect.Effect<void, never, WorkflowEngine.WorkflowEngine>;
  readonly resume: (
    executionId: string,
  ) => Effect.Effect<void, never, WorkflowEngine.WorkflowEngine>;
};

export type WorkflowRuntimeOptions = {
  readonly workflows: ReadonlyArray<Workflow.Any>;
  readonly events?: ReadonlyArray<AnyWorkflowEvent> | undefined;
  readonly definitionVersion?: ((workflow: Workflow.Any) => string) | undefined;
};

export interface WorkflowRuntimeService {
  readonly workflow: (name: string) => Effect.Effect<RunnableWorkflow, Error>;
  readonly event: (eventId: WorkflowEventId) => Effect.Effect<AnyWorkflowEvent, Error>;
  readonly version: (workflow: Workflow.Any) => string;
}

export class WorkflowRuntime extends Context.Service<WorkflowRuntime, WorkflowRuntimeService>()(
  "effect-zero/workflow/WorkflowRuntime",
) {}

const asRunnableWorkflow = (workflow: Workflow.Any): RunnableWorkflow =>
  workflow as RunnableWorkflow;

export const makeWorkflowRuntime = (options: WorkflowRuntimeOptions): WorkflowRuntimeService => {
  const workflowsByName = new Map(
    options.workflows.map((workflow) => [workflow.name, asRunnableWorkflow(workflow)]),
  );
  const eventsByName = new Map((options.events ?? []).map((event) => [event.name, event]));
  return {
    workflow: (name) =>
      Option.fromNullishOr(workflowsByName.get(name)).pipe(
        Option.match({
          onNone: () => Effect.fail(new Error(`Unknown workflow: ${name}`)),
          onSome: Effect.succeed,
        }),
      ),
    event: (eventId) =>
      parseWorkflowEventId(eventId).pipe(
        Effect.mapError((error) => new Error(error.message)),
        Effect.flatMap(({ eventName }) =>
          Option.fromNullishOr(eventsByName.get(eventName)).pipe(
            Option.match({
              onNone: () => Effect.fail(new Error(`Unknown workflow event: ${eventName}`)),
              onSome: Effect.succeed,
            }),
          ),
        ),
      ),
    version: options.definitionVersion ?? (() => "1"),
  };
};

export const workflowRuntimeLayer = (
  options: WorkflowRuntimeOptions,
): Layer.Layer<WorkflowRuntime> => Layer.succeed(WorkflowRuntime, makeWorkflowRuntime(options));

const encodeWorkflowPayload = (workflow: Workflow.Any, payload: unknown) =>
  Schema.encodeUnknownEffect(
    workflow.payloadSchema as unknown as Schema.Codec<unknown, unknown, never, never>,
  )(payload).pipe(Effect.flatMap(Schema.decodeUnknownEffect(Schema.Json)));

export type EnqueueWorkflowDefinitionOptions = {
  /** Stable invocation identity, generated by the caller before optimistic mutation. */
  readonly runId: string;
  readonly visibilityKey: string;
  readonly principal?: WorkflowJson | undefined;
  readonly maxAttempts?: number | undefined;
  readonly runAfter?: Date | undefined;
};

export const enqueueWorkflowDefinition = (
  workflow: Workflow.Any,
  payload: unknown,
  options: EnqueueWorkflowDefinitionOptions,
) =>
  Effect.gen(function* () {
    const store = yield* WorkflowStore;
    const runtime = yield* WorkflowRuntime;
    const executionId = yield* workflow.executionId(payload);
    const encodedPayload = yield* encodeWorkflowPayload(workflow, payload);
    return yield* store.enqueue({
      runId: options.runId,
      workflowName: workflow.name,
      definitionVersion: runtime.version(workflow),
      executionId,
      idempotencyKey: executionId,
      visibilityKey: options.visibilityKey,
      principal: options.principal,
      payload: encodedPayload,
      maxAttempts: options.maxAttempts,
      runAfter: options.runAfter,
    });
  });

const withWorkflowEngine =
  (engine: WorkflowEngine.WorkflowEngine["Service"]) =>
  <A, E>(effect: Effect.Effect<A, E, WorkflowEngine.WorkflowEngine>) =>
    effect.pipe(Effect.provideService(WorkflowEngine.WorkflowEngine, engine));

const executeStartCommand = (
  command: WorkflowCommand,
  workflow: RunnableWorkflow,
  engine: WorkflowEngine.WorkflowEngine["Service"],
  store: WorkflowStoreService,
) =>
  Effect.gen(function* () {
    const payload = yield* Schema.decodeUnknownEffect(
      workflow.payloadSchema as unknown as Schema.Codec<unknown, unknown, never, never>,
    )(command.payload);
    const executionId = yield* withWorkflowEngine(engine)(
      workflow.execute(payload, { discard: true }),
    );
    if (executionId !== command.executionId) {
      return yield* Effect.fail(
        new Error(
          `Workflow execution id mismatch for ${command.workflowName}: expected ${command.executionId}, received ${executionId}`,
        ),
      );
    }
    yield* store.markRun(command.runId, "running");
  });

const executeWorkflowCommand = (
  command: WorkflowCommand,
  runtime: WorkflowRuntimeService,
  engine: WorkflowEngine.WorkflowEngine["Service"],
  store: WorkflowStoreService,
) =>
  Effect.gen(function* () {
    const workflow = yield* runtime.workflow(command.workflowName);
    const currentVersion = runtime.version(workflow);
    if (currentVersion !== command.definitionVersion) {
      return yield* Effect.fail(
        new Error(
          `Workflow definition version mismatch for ${command.workflowName}: queued ${command.definitionVersion}, registered ${currentVersion}`,
        ),
      );
    }
    return yield* Match.value(command.kind).pipe(
      Match.when("start", () => executeStartCommand(command, workflow, engine, store)),
      Match.when("cancel", () =>
        withWorkflowEngine(engine)(workflow.interrupt(command.executionId)).pipe(
          Effect.andThen(store.markRun(command.runId, "cancelled")),
        ),
      ),
      Match.when("resume", () =>
        withWorkflowEngine(engine)(workflow.resume(command.executionId)).pipe(
          Effect.andThen(store.markRun(command.runId, "running")),
        ),
      ),
      Match.when("event", () =>
        Effect.gen(function* () {
          const payload = yield* Schema.decodeUnknownEffect(WorkflowEventCommandPayload)(
            command.payload,
          );
          const parsed = yield* parseWorkflowEventId(payload.eventId);
          if (
            parsed.workflowName !== command.workflowName ||
            parsed.executionId !== command.executionId
          ) {
            return yield* Effect.fail(
              new Error(
                `Workflow event ${payload.eventId} does not belong to execution ${command.executionId}`,
              ),
            );
          }
          const event = yield* runtime.event(payload.eventId);
          yield* withWorkflowEngine(engine)(event.sendUnknown(payload.eventId, payload.value));
          yield* store.markRun(command.runId, "running");
        }),
      ),
      Match.exhaustive,
    );
  });

export const workflowRuntimeCommandExecutorLayer = Layer.effect(
  WorkflowCommandExecutor,
  Effect.gen(function* () {
    const runtime = yield* WorkflowRuntime;
    const engine = yield* WorkflowEngine.WorkflowEngine;
    const store = yield* WorkflowStore;
    return {
      execute: (command: WorkflowCommand) =>
        executeWorkflowCommand(command, runtime, engine, store),
    };
  }),
);

const jsonOrDescription = (value: unknown): WorkflowJson =>
  Option.match(Schema.decodeUnknownOption(Schema.Json)(value), {
    onNone: () => ({ description: String(value) }),
    onSome: (json) => json,
  });

const hasMalformedMessageDefect = (cause: Cause.Cause<unknown>) =>
  cause.reasons.some(
    (reason) =>
      (Cause.isFailReason(reason) && ClusterError.MalformedMessage.is(reason.error)) ||
      (Cause.isDieReason(reason) && ClusterError.MalformedMessage.is(reason.defect)),
  );

const reconcileRun = (
  run: WorkflowRun,
  runtime: WorkflowRuntimeService,
  engine: WorkflowEngine.WorkflowEngine["Service"],
  store: WorkflowStoreService,
) =>
  Effect.gen(function* () {
    const workflow = yield* runtime.workflow(run.workflowName);
    const result = yield* withWorkflowEngine(engine)(workflow.poll(run.executionId));
    return yield* Match.valueTags(result, {
      None: () => Effect.void,
      Some: ({ value }) =>
        Match.valueTags(value, {
          Suspended: () => Effect.void,
          Complete: ({ exit }) =>
            Match.valueTags(exit, {
              Success: ({ value }) =>
                store.markRun(run.runId, "succeeded", {
                  result: jsonOrDescription(value),
                }),
              Failure: ({ cause }) =>
                store.markRun(run.runId, "failed", {
                  error: {
                    message: Cause.pretty(cause),
                  },
                }),
            }),
        }),
    });
  }).pipe(
    Effect.catchCause((cause) => {
      // Workflow.poll converts remote result-decoding failures to defects with
      // Effect.orDie. The execution is already terminal in storage, so record
      // that defect once instead of warning on every reconciliation forever.
      if (hasMalformedMessageDefect(cause)) {
        const reconciliationCause = Cause.pretty(cause);
        const runAnnotations = {
          executionId: run.executionId,
          runId: run.runId,
          workflowName: run.workflowName,
        };
        return store
          .markRun(run.runId, "failed", {
            error: {
              message: `Workflow execution state could not be decoded: ${reconciliationCause}`,
            },
          })
          .pipe(
            Effect.tap(() =>
              Effect.logWarning(
                "Marked workflow run as failed after undecodable execution state",
              ).pipe(
                Effect.annotateLogs({
                  ...runAnnotations,
                  cause: reconciliationCause,
                }),
              ),
            ),
            Effect.tapCause((markingCause) =>
              Effect.logError("Failed to mark workflow run after undecodable execution state").pipe(
                Effect.annotateLogs({
                  ...runAnnotations,
                  markingCause: Cause.pretty(markingCause),
                  reconciliationCause,
                }),
              ),
            ),
            Effect.ignore,
          );
      }
      return Effect.logWarning("Failed to reconcile workflow run").pipe(
        Effect.annotateLogs({
          cause: Cause.pretty(cause),
          executionId: run.executionId,
          runId: run.runId,
          workflowName: run.workflowName,
        }),
      );
    }),
  );

export const reconcileWorkflowRuns = (
  options: {
    readonly batchSize?: number | undefined;
    readonly concurrency?: number | undefined;
  } = {},
) =>
  Effect.gen(function* () {
    const runtime = yield* WorkflowRuntime;
    const engine = yield* WorkflowEngine.WorkflowEngine;
    const store = yield* WorkflowStore;
    const runs = yield* store
      .listRuns("running", options.batchSize ?? 100)
      .pipe(
        Effect.catchCause((cause) =>
          Effect.logError("Failed to list workflow runs for reconciliation", cause).pipe(
            Effect.as<ReadonlyArray<WorkflowRun>>([]),
          ),
        ),
      );
    yield* Effect.forEach(runs, (run) => reconcileRun(run, runtime, engine, store), {
      concurrency: options.concurrency ?? 10,
      discard: true,
    });
    return runs.length;
  });
